version: '3'
services:
  bf-mongo:
    container_name: bf-mongo
    hostname: bf-mongo
    image: mongo:4.4
    restart: unless-stopped
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=secret
      - MONGO_INITDB_DATABASE=sogogi

  bf-mysql:
    container_name: bf-mysql
    hostname: bf-mysql
    image: mariadb
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_USER=sogogi
      - MYSQL_PASSWORD=master
      - MYSQL_DATABASE=sogogi
      - TZ=Asia/Seoul
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      - /etc/localtime:/etc/localtime:ro

  beefproj:
    depends_on:
      - bf-mongo
      - bf-mysql
    container_name: beefproj
    hostname: beefproj
    image: beefproj/beefproj:latest
    restart: unless-stopped
    ports:
      - 30080:80
    environment:
      - DSN_MONGO=mongodb://root:secret@bf-mongo:27017/sogogi?authSource=admin
      - DSN_MYSQL=sogogi:master@tcp(bf-mysql:3306)/sogogi
